# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_uploaded', models.DateTimeField(verbose_name='date uploaded')),
                ('original_audio', models.CharField(max_length=500)),
                ('converted_audio', models.CharField(max_length=500)),
                ('state', models.CharField(choices=[('PROCESS', 'Process'), ('CONVERTED', 'Converted')], default='PROCESS', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('banner', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('guion', models.CharField(max_length=1000)),
                ('recommendations', models.CharField(max_length=1000)),
                ('valor', models.IntegerField(default=20)),
                ('date_begin', models.DateTimeField(verbose_name='date begin')),
                ('date_finish', models.DateTimeField(verbose_name='date finish')),
            ],
        ),
        migrations.CreateModel(
            name='File_contest_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervoices.Audio')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervoices.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('SPEAKER', 'Speaker')], default='ADMIN', max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.AddField(
            model_name='file_contest_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervoices.User'),
        ),
    ]
